// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("Capability")]
    public partial class Capability
    {
        public Capability()
        {
            FacilityCapabilities = new HashSet<FacilityCapability>();
        }

        [Key]
        public long CapabilityId { get; set; }
        [Required]
        [StringLength(1000)]
        public string CapabilityName { get; set; }

        [InverseProperty(nameof(FacilityCapability.Capability))]
        public virtual ICollection<FacilityCapability> FacilityCapabilities { get; set; }
    }
}