// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    public partial class FacilityCapability
    {
        [Key]
        public long FacilityCapabilityId { get; set; }
        public long FacilityId { get; set; }
        public long CapabilityId { get; set; }

        [ForeignKey(nameof(CapabilityId))]
        [InverseProperty("FacilityCapability")]
        public virtual Capability Capability { get; set; }
        [ForeignKey(nameof(FacilityId))]
        [InverseProperty("FacilityCapability")]
        public virtual Facility Facility { get; set; }
    }
}