// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("Facility")]
    [Index(nameof(OrganzationId), Name = "IX_Fk_Facility_Organization")]
    public partial class Facility
    {
        public Facility()
        {
            FacilityCapabilities = new HashSet<FacilityCapability>();
            Jobs = new HashSet<Job>();
        }

        [Key]
        public long FacilityId { get; set; }
        [Required]
        [StringLength(1000)]
        public string FacilityName { get; set; }
        public long OrganzationId { get; set; }
        [Required]
        [StringLength(1000)]
        public string Address { get; set; }
        [Required]
        [StringLength(1000)]
        public string Suburb { get; set; }
        [Required]
        [StringLength(1000)]
        public string City { get; set; }
        [Required]
        [StringLength(1000)]
        public string Country { get; set; }
        [Required]
        [StringLength(1000)]
        public string PhoneNumber1 { get; set; }
        [StringLength(1000)]
        public string PhoneNumber2 { get; set; }

        public bool IsActive { get; set; }

        [ForeignKey(nameof(OrganzationId))]
        [InverseProperty(nameof(Organization.Facilities))]
        public virtual Organization Organzation { get; set; }
        [InverseProperty(nameof(FacilityCapability.Facility))]
        public virtual ICollection<FacilityCapability> FacilityCapabilities { get; set; }
        [InverseProperty(nameof(Job.Facility))]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
