// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("JobStatus")]
    public partial class JobStatus
    {
        public JobStatus()
        {
            JobStatusChanges = new HashSet<JobStatusChange>();
        }

        [Key]
        public long JobStatusId { get; set; }
        [Required]
        [StringLength(1000)]
        public string JobStatusName { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }

        [InverseProperty(nameof(JobStatusChange.JobStatus))]
        public virtual ICollection<JobStatusChange> JobStatusChanges { get; set; }
    }
}