// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("JobStatusChange")]
    [Index(nameof(JobId), Name = "IX_JobId")]
    [Index(nameof(JobStatusId), Name = "IX_JobStatusChangeId")]
    public partial class JobStatusChange
    {
        [Key]
        public long JobStatusChangeId { get; set; }
        public long JobId { get; set; }
        public long? StaffId { get; set; }
        public long JobStatusId { get; set; }
        [Column("JobStatusChangeDateTimeUTC")]
        public DateTime JobStatusChangeDateTimeUtc { get; set; }
        [StringLength(1000)]
        public string JobStatusChangeReason { get; set; }
        [StringLength(1000)]
        public string JobStatusName { get; set; }
    }
}
