// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("JobSkill")]
    [Index(nameof(JobId), nameof(SkillId), Name = "IX_Fk_Jobskill_Job")]
    public partial class JobSkill
    {
        [Key]
        public long JobSkillId { get; set; }
        public long JobId { get; set; }
        public long SkillId { get; set; }

        [ForeignKey(nameof(JobId))]
        [InverseProperty("JobSkills")]
        public virtual Job Job { get; set; }
    }
}