// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    public partial class JobStatusChange
    {
        [Key]
        public long JobStatusChangeId { get; set; }
        public long JobId { get; set; }
        public long JobStatusId { get; set; }
        [Column("JobStatusChangeDateTimeUTC")]
        public DateTime JobStatusChangeDateTimeUtc { get; set; }
        [StringLength(1000)]
        public string JobStatusChangeReason { get; set; }

        [ForeignKey(nameof(JobId))]
        [InverseProperty("JobStatusChange")]
        public virtual Job Job { get; set; }
        [ForeignKey(nameof(JobStatusId))]
        [InverseProperty("JobStatusChange")]
        public virtual JobStatus JobStatus { get; set; }
    }
}