// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("Organization")]
    public partial class Organization
    {
        public Organization()
        {
            Facilities = new HashSet<Facility>();
        }

        [Key]
        public long OrganizationId { get; set; }
        public long TenantId { get; set; }
        [Required]
        [StringLength(1000)]
        public string OrganizationName { get; set; }
        [StringLength(1000)]
        public string Address { get; set; }

        [ForeignKey(nameof(TenantId))]
        [InverseProperty("Organizations")]
        public virtual Tenant Tenant { get; set; }
        [InverseProperty(nameof(Facility.Organzation))]
        public virtual ICollection<Facility> Facilities { get; set; }
    }
}