// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    public partial class Organization
    {
        public Organization()
        {
            Facility = new HashSet<Facility>();
        }

        [Key]
        public long OrganizationId { get; set; }
        [Required]
        [StringLength(1000)]
        public string OrganizationName { get; set; }

        [InverseProperty("Organzation")]
        public virtual ICollection<Facility> Facility { get; set; }
    }
}