// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("Organization")]
    [Index(nameof(Auth0OrganizationId), Name = "IX_Organization_Auth0OrganizationId", IsUnique = true)]
    public partial class Organization
    {
        public Organization()
        {
            Facilities = new HashSet<Facility>();
            Skills = new HashSet<Skill>();
            Staff = new HashSet<Staff>();
        }

        [Key]
        public long OrganizationId { get; set; }
        [Required]
        [StringLength(1000)]
        public string OrganizationName { get; set; }
        [Required]
        [StringLength(130)]
        public string Auth0OrganizationId { get; set; }
        [StringLength(1000)]
        public string Address { get; set; }
        [StringLength(1000)]
        public string Phone { get; set; }
        [StringLength(1000)]
        public string Comments { get; set; }
        public bool IsActive { get; set; }

        [InverseProperty(nameof(Facility.Organzation))]
        public virtual ICollection<Facility> Facilities { get; set; }
        [InverseProperty(nameof(Skill.Organization))]
        public virtual ICollection<Skill> Skills { get; set; }
        [InverseProperty("Organization")]
        public virtual ICollection<Staff> Staff { get; set; }
    }
}