// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("Skill")]
    public partial class Skill
    {
        [Key]
        public long SkillId { get; set; }
        [Required]
        [StringLength(1000)]
        public string SkillName { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }
    }
}