// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    public partial class Staff
    {
        public Staff()
        {
            StaffFacility = new HashSet<StaffFacility>();
            StaffSkill = new HashSet<StaffSkill>();
        }

        [Key]
        public long StaffId { get; set; }
        [Required]
        [StringLength(1000)]
        public string FirstName { get; set; }
        [StringLength(1000)]
        public string MiddleName { get; set; }
        [Required]
        [StringLength(1000)]
        public string LastName { get; set; }
        [StringLength(1000)]
        public string JobTitle { get; set; }
        public bool IsAvailable { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateOfBirth { get; set; }
        [StringLength(1000)]
        public string Email { get; set; }
        [StringLength(1000)]
        public string HomePhoneNumber { get; set; }
        [StringLength(1000)]
        public string MobilePhoneNumber { get; set; }
        [StringLength(1000)]
        public string OtherPhoneNumber { get; set; }
        [StringLength(1000)]
        public string Address { get; set; }
        [StringLength(1000)]
        public string Comments { get; set; }

        [InverseProperty("Staff")]
        public virtual ICollection<StaffFacility> StaffFacility { get; set; }
        [InverseProperty("Staff")]
        public virtual ICollection<StaffSkill> StaffSkill { get; set; }
    }
}