// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    [Table("StaffFacility")]
    public partial class StaffFacility
    {
        [Key]
        public long StaffFacilityId { get; set; }
        public long StaffId { get; set; }
        public long FacilityId { get; set; }

        [ForeignKey(nameof(StaffId))]
        [InverseProperty("StaffFacilities")]
        public virtual Staff Staff { get; set; }
    }
}