// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    public partial class Tenant
    {
        public Tenant()
        {
            Organization = new HashSet<Organization>();
        }

        [Key]
        public long TenantId { get; set; }
        [Required]
        [StringLength(1000)]
        public string TenantName { get; set; }

        [InverseProperty("Tenant")]
        public virtual ICollection<Organization> Organization { get; set; }
    }
}