trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts/rosterd-admin-ui-pipeline.yml
      - src/frontend

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
        npm run build
      displayName: 'npm ci and build'
      workingDirectory: 'src/frontend'

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: 'src/frontend/build'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'build'

- stage: DeployToDev
  displayName: Deploy To Dev
  jobs:
  - deployment: deploy
    pool:
      vmImage: 'windows-latest'
    variables:
      storageaccountname: strosterdstoragedev 
    environment: 'admin-ui-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: build

          - task: AzureFileCopy@3
            inputs:
              SourcePath: '$(Pipeline.Workspace)/build'
              azureSubscription: 'rosterd-service-connection'
              Destination: 'AzureBlob'
              storage: 'strosterdstoragedev'
              ContainerName: '$web'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'rosterd-service-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az cdn endpoint purge -g rg-rosterd-common --profile-name rosterd --content-paths "/$web/index.html" --name rosterd
