trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts/rosterd-admin-ui-pipeline.yml
      - src/frontend

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
      workingDirectory: 'src/frontend'

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: 'src/frontend/build'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'build'

- stage: DeployToDev
  displayName: Deploy To Dev
  jobs:
  - deployment: deploy
    environment: 'admin-ui-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: build
          - task: AzureStaticWebApp@0         
            inputs:
              app_location: $(Pipeline.Workspace)/build
              api_location: 'api'
              output_location: ''
              azure_static_web_apps_api_token: $(deployment_token)