trigger:
  branches:
    include:
      - main
  paths:
    include:
      - rosterd/scripts/rosterd-admin-ui-pipeline.yml
      - rosterd/src/frontend
      - scripts/rosterd-admin-ui-pipeline.yml
      - src/frontend

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        pwd
        ls -lA
        npm install
        npm run build
      displayName: 'npm install and build'
      workingDirectory: 'src/frontend'

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: 'src/frontend/build'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true

    - task: PublishBuildArtifacts@1      
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'build'

- stage: DeployToDev
  displayName: Deploy To Dev    
  jobs:
  - deployment: deploy
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      storageaccountname: strosterdstoragedev 
    environment: 'Deploy to Storage'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: build
              
          - task: AzureFileCopy@4
            inputs:
              sourcePath: $(Pipeline.Workspace)/build
              azureSubscription: 'Visual Studio Premium with MSDN (6d23c094-f45f-421c-9f59-fe097a0bcdc5)'
              Destination: 'AzureBlob'
              storage: 'strosterdstoragedev'
              ContainerName: '$web'