trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts/rosterd-public-website-ui-pipeline.yml
      - src/public-website

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: build
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
      workingDirectory: 'src/public-website'
    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/src/public-website/dist'
        api_location: 'api'
        output_location: ''
        azure_static_web_apps_api_token: $(deployment_token)

 
 