trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts/rosterd-admin-api-pipeline.yml
      - src/backend/Rosterd.Admin.Api

pool:
  vmImage: 'windows-latest'

########### BUILD Admin API ###########################################################################################################################

stages:
- stage: Build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore Packages
      inputs:
        command: restore
        projects: '**/*.csproj'

    - script: |
        dotnet build --configuration Release
      workingDirectory: 'src/backend/Rosterd.Admin.Api'
      displayName: "Build"

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: publish
        arguments: '--configuration Release --output publish_output'
        projects: 'src/backend/Rosterd.Admin.Api'
        publishWebProjects: false
        modifyOutputPath: false
        zipAfterPublish: false

    - task: ArchiveFiles@2
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build.zip"

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifacts"
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build.zip'
        artifactName: 'drop'

- stage: DeployToDev
  variables:
    - group: Rosterd-admin-api-dev
  displayName: Deploy To Dev
  jobs:
  - deployment: deploy
    pool:
      vmImage: 'windows-latest'
    environment: 'admin-api-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: drop
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'rosterd-service-connection'
              appType: 'webApp'
              WebAppName: 'app-rosterd-admin-api-dev'
              packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
              appSettings: 
                          '
                            -AppSettings:StaticDataCacheDurationMinutes "360"
                            -AppSettings:EventGridTopicEndpoint "https://evgt-rosterd-nonprod.westus2-1.eventgrid.azure.net/api/events"
                            -AppSettings:EventGridTopicKey "5iSIJsZ6sBWEf4u1TlbTQlylh3/ghgXOlfMkoWMVRUs="
                            -AppSettings:SearchServiceEndpoint "https://rosterd-dev-search.search.windows.net"
                            -AppSettings:SearchServiceApiKey "DE7B3AC40CDD847B2AB8B8427BF42E19"
                            -APPINSIGHTS_INSTRUMENTATIONKEY "DE7B3AC40CDD847B2AB8B8427BF42E19"
                            -ApplicationInsights:InstrumentationKey "7e2ebf37-9a6a-495a-81c6-2fcf6902cbb9"
                            -ConnectionStrings:SQLDBConnectionString "Server=tcp:sqls-rosterd-prod.database.windows.net,1433;Initial Catalog=rosterd;Persist Security Info=False;User ID=rosterd-admin-user;Password=K66pth1sS@f5;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
                            -ConnectionStrings:TableStorageConnectionString "DefaultEndpointsProtocol=https;AccountName=strosterdstoragedev;AccountKey=EoM27f5fmt0siT+uQmspne8jhgSdw9J55woZtn6CcpJzJVgHI9esz7nFOvMUQMMFMbG3L9IpjdLfRYrVXu1fzg==;EndpointSuffix=core.windows.net"
                            -Auth0Settings:Domain "rosterd-dev1.au.auth0.com"
                            -Auth0Settings:Audience "http://localhost:3000/dummy-api"
                            -Auth0Settings:ClientId "gCwuvFSdacLuQ86jd3eStnChowVpw2cc"
                            -Auth0Settings:ClientSecret "mM4svpI6f53vJMoD06ZKrjvKx5FdKnDfV0lWhBWRrPmj7vfbc58mEBtgVwKPCVw2"
                            -Auth0Settings:ConnectionId "con_EmhlZoAB3zEz6FOH"
                            -Auth0Settings:ConnectionName "Username-Password-Authentication"
                          '