trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts/rosterd-admin-api-pipeline.yml
      - src/backend/*
    exclude:
      - src/backend/Rosterd.Client.Api
      - src/backend/Rosterd.AzureFunctions

pool:
  vmImage: 'windows-latest'

########### BUILD Admin API ###########################################################################################################################

stages:
- stage: Build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - task: DotNetCoreCLI@2
      displayName: Restore Packages
      inputs:
        command: restore
        projects: '**/*.csproj'

    - script: |
        dotnet build --configuration Release
      workingDirectory: 'src/backend/Rosterd.Admin.Api'
      displayName: "Build"

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: publish
        arguments: '--configuration Release --output publish_output'
        projects: 'src/backend/Rosterd.Admin.Api'
        publishWebProjects: false
        modifyOutputPath: false
        zipAfterPublish: false

    - task: ArchiveFiles@2
      displayName: "Archive files"
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build.zip"

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifacts"
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/build.zip'
        artifactName: 'drop'

- stage: DeployToDev
  variables:
    - group: rosterd-admin-api-dev
  displayName: Deploy To Dev
  jobs:
  - deployment: deploy
    pool:
      vmImage: 'windows-latest'
    environment: 'admin-api-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: drop
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'rosterd-service-connection'
              appType: 'webApp'
              WebAppName: 'app-rosterd-admin-api-dev'
              packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
              appSettings: 
                          '
                            -AppSettings:StaticDataCacheDurationMinutes "360"
                            -AppSettings:EventGridTopicEndpoint "$(AppSettings.EventGridTopicEndpoint)"
                            -AppSettings:EventGridTopicKey "$(AppSettings.EventGridTopicKey)"
                            -AppSettings:SearchServiceEndpoint "$(AppSettings.SearchServiceEndpoint)"
                            -AppSettings:SearchServiceApiKey "$(AppSettings.SearchServiceApiKey)"
                            -APPINSIGHTS_INSTRUMENTATIONKEY "$(ApplicationInsights.InstrumentationKey)"
                            -ApplicationInsights:InstrumentationKey "$(ApplicationInsights.InstrumentationKey)"
                            -ConnectionStrings:SQLDBConnectionString "$(ConnectionStrings.SQLDBConnectionString)"
                            -ConnectionStrings:TableStorageConnectionString "$(ConnectionStrings.TableStorageConnectionString)"
                            -Auth0Settings:Domain "$(Auth0Settings.Domain)"
                            -Auth0Settings:Audience "$(Auth0Settings.Audience)"
                            -Auth0Settings:ClientId "$(Auth0Settings.ClientId)"
                            -Auth0Settings:ClientSecret "$(Auth0Settings.ClientSecret)"
                            -Auth0Settings:ConnectionId "$(Auth0Settings.ConnectionId)"
                            -Auth0Settings:ConnectionName "$(Auth0Settings.ConnectionName)"
                          '