/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** Success */
        200: unknown;
        /** Unauthorized */
        401: unknown;
        /** Forbidden */
        403: unknown;
      };
    };
  };
  "/api/v{version}/adminusers": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Auth0UserModelPagedList"];
            "application/json": components["schemas"]["Auth0UserModelPagedList"];
            "text/json": components["schemas"]["Auth0UserModelPagedList"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/adminusers/facility-admins": {
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StaffModel"];
            "application/json": components["schemas"]["StaffModel"];
            "text/json": components["schemas"]["StaffModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The admin to add for the facility */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddAdminWhoIsAlsoStaffRequest"];
          "text/json": components["schemas"]["AddAdminWhoIsAlsoStaffRequest"];
          "application/*+json": components["schemas"]["AddAdminWhoIsAlsoStaffRequest"];
        };
      };
    };
  };
  "/api/v{version}/adminusers/organization-admins": {
    put: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Auth0UserModel"];
            "application/json": components["schemas"]["Auth0UserModel"];
            "text/json": components["schemas"]["Auth0UserModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The organization admin member to update */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateAdminUserRequest"];
          "text/json": components["schemas"]["UpdateAdminUserRequest"];
          "application/*+json": components["schemas"]["UpdateAdminUserRequest"];
        };
      };
    };
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Auth0UserModel"];
            "application/json": components["schemas"]["Auth0UserModel"];
            "text/json": components["schemas"]["Auth0UserModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The admin to add for the organization */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddAdminUserRequest"];
          "text/json": components["schemas"]["AddAdminUserRequest"];
          "application/*+json": components["schemas"]["AddAdminUserRequest"];
        };
      };
    };
  };
  "/api/v{version}/adminusers/organization-admins/{auth0userid}": {
    delete: {
      parameters: {
        path: {
          /** The admin to remove from auth0 */
          auth0UserId: string;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/facilities": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["FacilityModelPagedList"];
            "application/json": components["schemas"]["FacilityModelPagedList"];
            "text/json": components["schemas"]["FacilityModelPagedList"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    put: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["FacilityModel"];
            "application/json": components["schemas"]["FacilityModel"];
            "text/json": components["schemas"]["FacilityModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Facility to update */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateFacilityRequest"];
          "text/json": components["schemas"]["UpdateFacilityRequest"];
          "application/*+json": components["schemas"]["UpdateFacilityRequest"];
        };
      };
    };
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["FacilityModel"];
            "application/json": components["schemas"]["FacilityModel"];
            "text/json": components["schemas"]["FacilityModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Facility to add */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddFacilityRequest"];
          "text/json": components["schemas"]["AddFacilityRequest"];
          "application/*+json": components["schemas"]["AddFacilityRequest"];
        };
      };
    };
  };
  "/api/v{version}/facilities/{facilityid}": {
    get: {
      parameters: {
        path: {
          facilityId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["FacilityModel"];
            "application/json": components["schemas"]["FacilityModel"];
            "text/json": components["schemas"]["FacilityModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          /** The Facility to be deleted */
          facilityId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/facilities/{facilityid}/reactivate": {
    patch: {
      parameters: {
        path: {
          /** The facility id to update */
          facilityId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/Jobs": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["JobModelPagedList"];
            "application/json": components["schemas"]["JobModelPagedList"];
            "text/json": components["schemas"]["JobModelPagedList"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Job to add */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddJobRequest"];
          "text/json": components["schemas"]["AddJobRequest"];
          "application/*+json": components["schemas"]["AddJobRequest"];
        };
      };
    };
  };
  "/api/v{version}/Jobs/{jobId}": {
    get: {
      parameters: {
        path: {
          jobId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["JobModel"];
            "application/json": components["schemas"]["JobModel"];
            "text/json": components["schemas"]["JobModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          /** The Job to be removed */
          jobId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The reason for the job cancellation */
      requestBody: {
        content: {
          "application/json": string;
          "text/json": string;
          "application/*+json": string;
        };
      };
    };
  };
  "/api/v{version}/Organizations": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
          /**
           * True = only active organizations will be returned.
           *             False = all organization will be returned
           *             The default is true
           */
          activeOrganizationsOnly?: boolean;
        };
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["OrganizationModelPagedList"];
            "application/json": components["schemas"]["OrganizationModelPagedList"];
            "text/json": components["schemas"]["OrganizationModelPagedList"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    put: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["OrganizationModel"];
            "application/json": components["schemas"]["OrganizationModel"];
            "text/json": components["schemas"]["OrganizationModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Organization to update */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateOrganizationRequest"];
          "text/json": components["schemas"]["UpdateOrganizationRequest"];
          "application/*+json": components["schemas"]["UpdateOrganizationRequest"];
        };
      };
    };
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["OrganizationModel"];
            "application/json": components["schemas"]["OrganizationModel"];
            "text/json": components["schemas"]["OrganizationModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Organization to add */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddOrganizationRequest"];
          "text/json": components["schemas"]["AddOrganizationRequest"];
          "application/*+json": components["schemas"]["AddOrganizationRequest"];
        };
      };
    };
  };
  "/api/v{version}/Organizations/{organizationId}": {
    get: {
      parameters: {
        path: {
          organizationId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["OrganizationModel"];
            "application/json": components["schemas"]["OrganizationModel"];
            "text/json": components["schemas"]["OrganizationModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          /** The Organization to be deleted */
          organizationId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/Roles": {
    get: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RosterdRole"][];
            "application/json": components["schemas"]["RosterdRole"][];
            "text/json": components["schemas"]["RosterdRole"][];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The role to add */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddRoleRequest"];
          "text/json": components["schemas"]["AddRoleRequest"];
          "application/*+json": components["schemas"]["AddRoleRequest"];
        };
      };
    };
  };
  "/api/v{version}/Roles/{roleId}": {
    get: {
      parameters: {
        path: {
          roleId: string;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["RosterdRole"];
            "application/json": components["schemas"]["RosterdRole"];
            "text/json": components["schemas"]["RosterdRole"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          /** The role to be deleted */
          roleId: string;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/Skills": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SkillModelPagedList"];
            "application/json": components["schemas"]["SkillModelPagedList"];
            "text/json": components["schemas"]["SkillModelPagedList"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    put: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SkillModel"];
            "application/json": components["schemas"]["SkillModel"];
            "text/json": components["schemas"]["SkillModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Skill to update */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateSkillRequest"];
          "text/json": components["schemas"]["UpdateSkillRequest"];
          "application/*+json": components["schemas"]["UpdateSkillRequest"];
        };
      };
    };
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SkillModel"];
            "application/json": components["schemas"]["SkillModel"];
            "text/json": components["schemas"]["SkillModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Skill to add */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddSkillRequest"];
          "text/json": components["schemas"]["AddSkillRequest"];
          "application/*+json": components["schemas"]["AddSkillRequest"];
        };
      };
    };
  };
  "/api/v{version}/Skills/{skillId}": {
    get: {
      parameters: {
        path: {
          skillId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["SkillModel"];
            "application/json": components["schemas"]["SkillModel"];
            "text/json": components["schemas"]["SkillModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          /** The Skill to be deleted */
          skillId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/Staff": {
    get: {
      parameters: {
        query: {
          pageNumber?: number;
          pageSize?: number;
        };
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StaffModelPagedList"];
            "application/json": components["schemas"]["StaffModelPagedList"];
            "text/json": components["schemas"]["StaffModelPagedList"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
    put: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StaffModel"];
            "application/json": components["schemas"]["StaffModel"];
            "text/json": components["schemas"]["StaffModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Staff member to update */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateStaffRequest"];
          "text/json": components["schemas"]["UpdateStaffRequest"];
          "application/*+json": components["schemas"]["UpdateStaffRequest"];
        };
      };
    };
    post: {
      parameters: {
        path: {
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StaffModel"];
            "application/json": components["schemas"]["StaffModel"];
            "text/json": components["schemas"]["StaffModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The Staff member to add */
      requestBody: {
        content: {
          "application/json": components["schemas"]["AddStaffRequest"];
          "text/json": components["schemas"]["AddStaffRequest"];
          "application/*+json": components["schemas"]["AddStaffRequest"];
        };
      };
    };
  };
  "/api/v{version}/Staff/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StaffModel"];
            "application/json": components["schemas"]["StaffModel"];
            "text/json": components["schemas"]["StaffModel"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/Staff/{staffId}": {
    delete: {
      parameters: {
        path: {
          /** The Staff member to mark as inactive */
          staffId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/Staff/{staffId}/reactivate": {
    patch: {
      parameters: {
        path: {
          /** The staff id to update */
          staffId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/api/v{version}/Staff/{staffId}/skills": {
    put: {
      parameters: {
        path: {
          /** The Staff id */
          staffId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The skills to add */
      requestBody: {
        content: {
          "application/json": components["schemas"]["SkillsToStaffRequest"];
          "text/json": components["schemas"]["SkillsToStaffRequest"];
          "application/*+json": components["schemas"]["SkillsToStaffRequest"];
        };
      };
    };
    delete: {
      parameters: {
        path: {
          /** The Staff id */
          staffId: number;
          version: string;
        };
      };
      responses: {
        /** Success */
        200: unknown;
        /** Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Unauthorized */
        401: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Forbidden */
        403: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Not Found */
        404: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        422: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Client Error */
        429: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
      /** The skills to delete */
      requestBody: {
        content: {
          "application/json": components["schemas"]["SkillsToStaffRequest"];
          "text/json": components["schemas"]["SkillsToStaffRequest"];
          "application/*+json": components["schemas"]["SkillsToStaffRequest"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    AddAdminUserRequest: {
      /** The auth0 organization id to add this admin too */
      auth0OrganizationId?: string | null;
      firstName: string;
      lastName: string;
      email: string;
      phoneNumber?: string | null;
    };
    AddAdminWhoIsAlsoStaffRequest: {
      firstName: string;
      lastName: string;
      email: string;
      phoneNumber?: string | null;
      middleName?: string | null;
      mobilePhoneNumber?: string | null;
      dateOfBirth?: string | null;
      address?: string | null;
      comments?: string | null;
      jobTitle?: string | null;
      /** The list of skills that the staff has, when creating should at least have one */
      skillIds?: number[] | null;
    };
    AddFacilityRequest: {
      facilityName: string;
      address: string;
      suburb?: string | null;
      city: string;
      country: string;
      latitude: number;
      longitude: number;
      phoneNumber1: string;
      phoneNumber2?: string | null;
    };
    AddJobRequest: {
      jobTitle: string;
      description: string;
      facilityId: number;
      jobStartDateTimeUtc: string;
      jobEndDateTimeUtc: string;
      comments?: string | null;
      gracePeriodToCancelMinutes?: number | null;
      noGracePeriod?: boolean | null;
      responsibilities?: string | null;
      experience?: string | null;
      isNightShift?: boolean;
      skillsRequiredForJob?: number[] | null;
    };
    AddOrganizationRequest: {
      organizationName: string;
      phone?: string | null;
      address?: string | null;
      comments?: string | null;
    };
    AddRoleRequest: {
      roleName: string;
      roleDescription: string;
    };
    AddSkillRequest: {
      skillName: string;
      description?: string | null;
    };
    AddStaffRequest: {
      firstName: string;
      lastName: string;
      email: string;
      mobilePhoneNumber?: string | null;
      comments?: string | null;
      jobTitle?: string | null;
      /** The list of skills that the staff has, when creating should at least have one */
      skillIds?: number[] | null;
    };
    Auth0UserModel: {
      userAuth0Id: string;
      firstName: string;
      lastName: string;
      email: string;
      mobilePhoneNumber?: string | null;
      rosterdRolesForUser?: components["schemas"]["RosterdRoleEnum"][] | null;
    };
    Auth0UserModelPagedList: {
      currentPage?: number;
      totalPages?: number;
      pageSize?: number;
      totalCount?: number;
      hasPrevious?: boolean;
      hasNext?: boolean;
      items?: components["schemas"]["Auth0UserModel"][] | null;
    };
    FacilityCapabilityModel: { [key: string]: unknown };
    FacilityModel: {
      facilityId?: number;
      facilityName: string;
      address: string;
      suburb?: string | null;
      city: string;
      country: string;
      latitude: number;
      longitude: number;
      phoneNumber1: string;
      isActive: boolean;
      phoneNumber2?: string | null;
      organization?: components["schemas"]["OrganizationModel"];
      facilityCapabilities?:
        | components["schemas"]["FacilityCapabilityModel"][]
        | null;
    };
    FacilityModelPagedList: {
      currentPage?: number;
      totalPages?: number;
      pageSize?: number;
      totalCount?: number;
      hasPrevious?: boolean;
      hasNext?: boolean;
      items?: components["schemas"]["FacilityModel"][] | null;
    };
    JobModel: {
      jobId?: number;
      jobTitle: string;
      description: string;
      facility?: components["schemas"]["FacilityModel"];
      jobStartDateTimeUtc: string;
      jobEndDateTimeUtc: string;
      jobPostedDateTimeUtc: string;
      comments?: string | null;
      gracePeriodToCancelMinutes: number;
      noGracePeriod?: boolean | null;
      jobGracePeriodEndDateTimeUtc?: string | null;
      jobStatus: components["schemas"]["JobStatus"];
      jobStatusName?: string | null;
      responsibilities?: string | null;
      experience?: string | null;
      isNightShift?: boolean;
      jobSkills?: components["schemas"]["JobSkillModel"][] | null;
    };
    JobModelPagedList: {
      currentPage?: number;
      totalPages?: number;
      pageSize?: number;
      totalCount?: number;
      hasPrevious?: boolean;
      hasNext?: boolean;
      items?: components["schemas"]["JobModel"][] | null;
    };
    JobSkillModel: {
      jobSkillId?: number;
      jobId?: number;
      skillId?: number;
      skillName?: string | null;
    };
    JobStatus:
      | "Published"
      | "Accepted"
      | "NoShow"
      | "InProgress"
      | "FeedbackPending"
      | "Completed"
      | "Expired"
      | "Cancelled";
    OrganizationModel: {
      organizationId?: number;
      auth0OrganizationId?: string | null;
      organizationName: string;
      phone?: string | null;
      address?: string | null;
      comments?: string | null;
      isActive?: boolean;
    };
    OrganizationModelPagedList: {
      currentPage?: number;
      totalPages?: number;
      pageSize?: number;
      totalCount?: number;
      hasPrevious?: boolean;
      hasNext?: boolean;
      items?: components["schemas"]["OrganizationModel"][] | null;
    };
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
    } & { [key: string]: any };
    RosterdRole: {
      roleId?: string | null;
      roleName?: string | null;
      roleDescription?: string | null;
    };
    RosterdRoleEnum:
      | "OrganizationAdmin"
      | "RosterdAdmin"
      | "FacilityAdmin"
      | "Staff";
    SkillModel: {
      skillId?: number;
      skillName: string;
      description?: string | null;
    };
    SkillModelPagedList: {
      currentPage?: number;
      totalPages?: number;
      pageSize?: number;
      totalCount?: number;
      hasPrevious?: boolean;
      hasNext?: boolean;
      items?: components["schemas"]["SkillModel"][] | null;
    };
    SkillsToStaffRequest: {
      skills?: number[] | null;
    };
    StaffModel: {
      staffId?: number | null;
      auth0Id?: string | null;
      firstName: string;
      lastName: string;
      email: string;
      mobilePhoneNumber?: string | null;
      isActive?: boolean;
      comments?: string | null;
      jobTitle?: string | null;
      staffSkills?: components["schemas"]["SkillModel"][] | null;
    };
    StaffModelPagedList: {
      currentPage?: number;
      totalPages?: number;
      pageSize?: number;
      totalCount?: number;
      hasPrevious?: boolean;
      hasNext?: boolean;
      items?: components["schemas"]["StaffModel"][] | null;
    };
    UpdateAdminUserRequest: {
      /** The auth0 organization id to add this admin too */
      auth0OrganizationId?: string | null;
      /** The users auth0 id */
      auth0UserId: string;
      firstName: string;
      lastName: string;
      phoneNumber?: string | null;
    };
    UpdateFacilityRequest: {
      facilityId?: number;
      facilityName: string;
      address: string;
      suburb?: string | null;
      city: string;
      country: string;
      latitude: number;
      longitude: number;
      phoneNumber1: string;
      phoneNumber2?: string | null;
    };
    UpdateOrganizationRequest: {
      organizationId?: number;
      organizationName: string;
      phone?: string | null;
      address?: string | null;
      comments?: string | null;
    };
    UpdateSkillRequest: {
      skillId: number;
      skillName: string;
      description?: string | null;
    };
    UpdateStaffRequest: {
      staffId?: number | null;
      firstName: string;
      lastName: string;
      mobilePhoneNumber?: string | null;
      comments?: string | null;
      jobTitle?: string | null;
    };
  };
}

export interface operations {}

export interface external {}
