// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    public partial class Facility
    {
        public Facility()
        {
            FacilityCapability = new HashSet<FacilityCapability>();
        }

        [Key]
        public long FacilityId { get; set; }
        [Required]
        [StringLength(1000)]
        public string FacilityName { get; set; }
        public long OrganzationId { get; set; }

        [ForeignKey(nameof(OrganzationId))]
        [InverseProperty(nameof(Organization.Facility))]
        public virtual Organization Organzation { get; set; }
        [InverseProperty("Facility")]
        public virtual ICollection<FacilityCapability> FacilityCapability { get; set; }
    }
}