// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Rosterd.Data.SqlServer.Models
{
    public partial class Resource
    {
        [Key]
        public long ResourceId { get; set; }
        [Required]
        [StringLength(1000)]
        public string FirstName { get; set; }
        [StringLength(1000)]
        public string MiddleName { get; set; }
        [Required]
        [StringLength(1000)]
        public string LastName { get; set; }
    }
}