name: app-ui

on:
  push:
    branches: 
      - main
      - 'feature/**'
    paths:
      - 'README.md'

  workflow_dispatch:

env:
  BUILD_ARGS: "ABC"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2