name: functions

on:
  push:
    branches: 
      - main
      - 'feature/**'
    paths:
      - 'src/backend/*'
      - '.github/workflows/functions.yaml'
      - '!**/README.md'
      - '!src/backend/Rosterd.Client.Api'
      - '!src/backend/Rosterd.Admin.Api'

  workflow_dispatch:

env:
  BUILD_ARGS: "ABC"

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        working-directory: 'src/backend'
        run: dotnet restore Rosterd.Backend.sln
        
      - name: Build
        working-directory: 'src/backend/Rosterd.AzureFunctions'
        run: dotnet build -c Release --no-restore
