name: public-website

on:
  push:
    branches: 
      - main
      - 'feature/**'
    paths:
      - 'src/public-website'
      - '.github/workflows/public-website.yaml'
      - '!**/README.md'

  workflow_dispatch:

env:
  BUILD_ARGS: "ABC"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2